vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone = "eu-central-1a"
env_prefix = "dev"
instance_type = "t2.micro"
public_key_location = "/home/cheider/.ssh/id_rsa.pub"
private_key = "/home/cheider/.ssh/id_rsa"